import {useState} from 'react';
import {ControlExplorer} from './color-tools';

function Evidence({ids}:{ids:string[]}){return <p className="caption quiet">Research context: {ids.map(id=><a key={id} href="#research">[{id}] </a>)} · See the searchable evidence library for scope and limitations.</p>}
const doors=[['Favorite player','A recognizable player opens the door. What remains when that player leaves?','R05 / R06'],['Family','A shared ritual can make a club feel familiar before you choose it yourself.','R02 / R22'],['World Cup','An event can spark curiosity. A club needs a reason to hold it.','R01'],['Video game','Learning the names is a possible introduction; playing a game is not proof of club attachment.','R21'],['Social media','Repeated encounters can bring a distant club into everyday life.','R21'],['Friends','The people watching with you may become part of what you return for.','R03 / R23'],['First live match','Being there creates an opportunity for connection, not a guarantee.','R03'],['Television','A viewing routine can create familiarity across an ocean.','R21 / R22'],['Local club','Place can supply meaning. A postcode cannot choose your team for you.','R02'],['International club','History, players and community offer possible routes across borders.','R22 / R23']];
export function FandomPath(){const [selected,setSelected]=useState<number[]>([]);return <div className="explorer"><span className="label application">Exploratory application · RQ1</span><h3>How did you get here?</h3><p>Choose up to three entrances. The interesting part is why you stayed.</p><div className="switches">{doors.map(([name],i)=><button key={name} aria-pressed={selected.includes(i)} disabled={selected.length===3&&!selected.includes(i)} onClick={()=>setSelected(s=>s.includes(i)?s.filter(n=>n!==i):[...s,i])}>{name}</button>)}</div><div className="path-stages" aria-label="Possible dimensions of connection">{['Awareness','Attraction','Attachment','Identity','Allegiance'].map((s,i)=><div key={s}><small>0{i+1}</small><strong>{s}</strong><span>{['I know them.','I enjoy them.','They mean something.','They are part of me.','I keep returning.'][i]}</span></div>)}</div><div aria-live="polite" className="path-output">{selected.length?selected.map(i=><article key={i}><strong>{doors[i][0]}</strong><p>{doors[i][1]}</p><small>Context: {doors[i][2]}</small></article>):<p className="quiet">Select an entrance to uncover a question worth following.</p>}</div><p className="caption quiet">Conceptual prompts, not measured effects of these entry points. Identity is added as a separate lens to the PCM’s four levels. Paths can overlap, pause or change; this is not a diagnostic score. Your selections are not saved.</p><Evidence ids={['R01','R02','R20','R21','R22','R23']}/></div>}
const rituals=['Matchday routine','Transfer news','Highlights','Podcasts','Supporter friends','Club history'];
export function Presence(){const [chosen,setChosen]=useState<string[]>(['Matchday routine','Supporter friends']);return <div className="presence explorer"><div><span className="eyebrow">Distance vs presence</span><h3>Far away.<br/>Always around.</h3><p>Geography says Missouri. Your shirt says London.</p><p className="caption quiet">Toggle the ways a distant club might show up in a fan’s week. This is an illustrative routine, not an emotional-closeness scale.</p></div><div><div className="switches">{rituals.map(r=><button key={r} aria-pressed={chosen.includes(r)} onClick={()=>setChosen(c=>c.includes(r)?c.filter(x=>x!==r):[...c,r])}>{r}</button>)}</div><div className="presence-orbit" aria-live="polite"><strong>A fan’s everyday life</strong>{chosen.length?chosen.map(r=><span key={r}>{r}</span>):<p>No routines selected. Distance alone still cannot explain attachment.</p>}</div><p className="caption quiet">The ocean stays put. The opportunities for contact change. Local clubs can build these routines too.</p><Evidence ids={['R21','R23']}/></div></div>}
const comparisons=[
['Proximity','A local match can offer in-person rituals and community participation. Travel, price and welcome still matter.','A distant club can be present through viewing groups and media. Access to its home stadium is a different proposition.','Living nearby is an opportunity for contact, not evidence of attachment.'],
['Identity','City symbols and shared local experiences can give a club personal meaning.','An overseas club can connect a fan to heritage, friends or an adopted community.','Local and global identities can coexist. Neither automatically feels more authentic.'],
['Players','A recognizable player can draw attention; linking that interest to the club is a separate task.','A familiar player can introduce an overseas club; that fan may stay for other reasons.','Star recognition, attendance and lasting identification are different outcomes.'],
['History + prestige','A younger club can build rituals around experiences supporters actually share.','An established club’s history can offer stories that a distant supporter adopts.','History cannot be manufactured overnight. Prestige is an association to investigate, not a quality statistic.'],
['Media familiarity','Repeated player and community stories can make the club recognizable between matches.','Viewing routines, digital content and supporter groups can sustain contact from abroad.','Exposure is not the same as affection. Ask what contact means to a fan.'],
['Quality','Look at defined dimensions of the soccer and report the limits of comparable evidence.','Use the same definitions, period and context before interpreting an apparent difference.','No overall league score here. Choose a quality dimension in the next section.']
];
export function LeagueComparison(){const [active,setActive]=useState(0);const c=comparisons[active];return <div className="explorer"><span className="eyebrow">Different forms of value / RQ2</span><h3>Two leagues.<br/>More than one reason.</h3><p>Choose a lens. Leave the winner’s podium in storage.</p><div className="switches" aria-label="Comparison category">{comparisons.map(([name],i)=><button key={name} aria-pressed={active===i} onClick={()=>setActive(i)}>{name}</button>)}</div><div aria-live="polite"><div className="league-pair"><article><span className="eyebrow">MLS / local opportunity</span><h4>{c[0]}</h4><p>{c[1]}</p></article><article><span className="eyebrow">Premier League / overseas connection</span><h4>{c[0]}</h4><p>{c[2]}</p></article></div><p className="comparison-note"><strong>Interpretation: </strong>{c[3]}</p></div><details><summary>Research context and limits</summary><p>These are research-informed comparison lenses, not measured league rankings. Community identity and transnational fandom frame the questions. Historical star-player attendance studies do not establish present-day attachment effects.</p><Evidence ids={['R02','R05','R06','R21','R22','R23']}/></details></div>}
const dimensions=[
{title:'Passing',belief:'“Better teams keep the ball better.”',measure:'Pass completion, progression and pass difficulty, using consistent event definitions.',limit:'Completion alone rewards safe passes. Opponent pressure, field position and game state change the task.'},
{title:'Chance creation',belief:'“More chances means better soccer.”',measure:'Shots, shot locations and expected goals from the same provider and model.',limit:'More chances may reflect weak defending. Expected-goals values from different models are not directly interchangeable.'},
{title:'Possession',belief:'“More of the ball means more quality.”',measure:'Possession share alongside territory, score state and attacking outcomes.',limit:'Possession describes control of the ball, not automatically the value created with it.'},
{title:'Tempo',belief:'“Faster must mean better.”',measure:'Defined measures such as ball-in-play time, sequence duration or progression speed.',limit:'These measure different kinds of speed. Faster decisions, faster running and shorter possessions are not the same thing.'},
{title:'Player profiles',belief:'“Famous players settle the argument.”',measure:'Age, minutes, roles and international representation within a specified season.',limit:'Recognition is not performance. National-team selection depends on eligibility, competition and selection policy.'},
{title:'Competitive balance',belief:'“Unpredictable games mean a stronger league.”',measure:'Points dispersion or outcome concentration over comparable seasons and competition formats.',limit:'Uncertainty of outcome and absolute playing standard are distinct. Different schedules complicate comparison.'},
{title:'Player movement',belief:'“Transfers tell us which league is better.”',measure:'Player minutes and roles before and after a move, with age and adaptation time recorded.',limit:'Transfers are selected cases. A transfer fee or one successful player cannot represent an entire league.'}
];
export function ProductLab(){const [active,setActive]=useState(0);const d=dimensions[active];return <><div className="reputation-grid"><article><span className="eyebrow orange">Premier League associations to examine</span><h3>Historic. Global.<br/>Prestigious?</h3></article><article><span className="eyebrow orange">MLS associations to examine</span><h3>Local. Younger.<br/>Growing?</h3></article></div><p className="caption quiet">Illustrative reputation prompts, not universal beliefs or measured American responses. Cultural and transnational-fandom literature supplies context; it does not establish the prevalence of these labels. <a href="#research">R17 · R21 · R22 · R23</a></p><div className="explorer product-lab"><span className="label">Perception vs product / RQ3</span><h3>The name arrives<br/>before the ball moves.</h3><p>But “quality” needs a definition. Select what you want to examine.</p><div className="switches" aria-label="Quality dimension">{dimensions.map((x,i)=><button key={x.title} aria-pressed={active===i} onClick={()=>setActive(i)}>{x.title}</button>)}</div><div className="product-cards" aria-live="polite"><article><span className="label">01 / Perception prompt</span><h4>{d.belief}</h4><p className="caption">Illustrative assumption to question, not a participant quote or documented finding.</p></article><article><span className="label application">02 / Observable product</span><h4>What could we inspect?</h4><p>{d.measure}</p></article><article><span className="label">03 / Interpretation</span><h4>What does it leave out?</h4><p>{d.limit}</p></article></div><details className="rule"><summary>How this addresses RQ3 responsibly</summary><p>Compare documented perceptions in existing American-fan research with defined characteristics in comparable published soccer data. Record the season, sample, provider and definition. Where matching evidence is unavailable, leave the comparison unresolved.</p><p>No comparable cross-league dataset is loaded here. These are methodological prompts, not league performance findings. The current source collection supports fandom context; it does not yet substantiate an answer to every quality question.</p></details><p className="caption quiet">Secondary research only. No blind-evaluation experiment, surveys or participant responses are collected.</p></div></>}
const problems=[
{title:'People do not know our players.',issue:'Player recognition',examine:'Separate recognition of individual stars from recognition of the team and wider roster.',influence:'Recurring player introductions tied to the club, its people and its city.',boundary:'Marketing cannot guarantee star recruitment or transfer a player’s following to the team.',action:'Test a short player-story series. Track voluntary repeat viewing and club-content exploration, not just reach.',refs:['R05','R06']},
{title:'People know our club but do not care.',issue:'Attachment / identity',examine:'Look for the communities and experiences that make the club personally relevant.',influence:'Supporter access, welcoming rituals and credible community relationships.',boundary:'City branding alone cannot manufacture belonging.',action:'Co-create a newcomer experience with existing supporters. Examine repeat participation and barriers to returning.',refs:['R02','R20']},
{title:'People love soccer but ignore MLS.',issue:'Competing attachment',examine:'Look at existing club loyalties, viewing routines and what an MLS experience could add.',influence:'Invitations that welcome dual fandom and offer a distinct local experience.',boundary:'A campaign cannot erase another club’s accumulated meaning.',action:'Pilot a local match invitation through an overseas-club supporter community without asking anyone to switch teams.',refs:['R22','R23']},
{title:'Fans assume our league is inferior.',issue:'Reputation / quality perception',examine:'Clarify whether the concern is play, prestige, broadcast presentation or unfamiliarity.',influence:'Honest presentation, understandable player stories and evidence for specific claims.',boundary:'A slogan cannot change the level of play or remove financial and competitive constraints.',action:'Build a narrowly defined product comparison. If data are not comparable, state the gap instead of selling superiority.',refs:['R21','R22']},
{title:'People attend but do not stay connected.',issue:'Relationship depth',examine:'Distinguish one-off attendance from relationships with the club and other supporters.',influence:'Between-match contact, community participation and opportunities to return together.',boundary:'An attendance count cannot establish loyalty or explain why someone disappears.',action:'Offer an opt-in post-match community follow-up. Compare repeat engagement with attendance, keeping the measures separate.',refs:['R03','R04','R10']}
];
export function ClubDecision(){const [active,setActive]=useState(0);const p=problems[active];return <><div className="application-photo"><img src="/fcc-supporters.svg" width="1600" height="1067" loading="lazy" alt="FC Cincinnati supporters sharing a matchday with flags and club colors"/><div><span className="eyebrow">From an audience to a community</span><h3>Give the connection<br/>somewhere to go.</h3><p>Practical application: create a reason to return together.</p><a href="#credits">Jamie Smed / CC BY 2.0 · Image credit</a></div></div><div className="fan-transition"><span className="eyebrow orange">The soccer fan MLS doesn’t have to convince</span><h3>Loves soccer. Watches soccer.<br/>Buys the shirt. Knows the players.</h3><p>Still might not care about MLS.</p><strong>So where did the attachment go?</strong></div><ControlExplorer/><div className="explorer decision-tool"><span className="label application">Research-informed application</span><h3>What problem are you<br/>actually trying to solve?</h3><div className="decision-layout"><div className="decision-options" aria-label="Choose an organizational challenge">{problems.map((x,i)=><button key={x.issue} aria-pressed={active===i} onClick={()=>setActive(i)}>{x.title}<span aria-hidden="true">↗</span></button>)}</div><div className="decision-result" aria-live="polite"><span className="eyebrow orange">Possible issue</span><h4>{p.issue}</h4><dl><dt>Examine</dt><dd>{p.examine}</dd><dt>You may influence</dt><dd>{p.influence}</dd><dt>Marketing cannot do it alone</dt><dd>{p.boundary}</dd><dt>A direction to test</dt><dd>{p.action}</dd></dl><Evidence ids={p.refs}/></div></div><p className="caption quiet">A planning aid, not a validated diagnosis or a promised result. The cited research informs the lens; the proposed action is an application to test.</p></div></>}
