import {useState} from 'react';
import {ControlExplorer} from './color-tools';
import {sources} from './data';

function Evidence({ids}:{ids:string[]}){return <p className="caption quiet">Research context: {ids.map(id=><a key={id} href={sources.find(s=>s.id===id)?.url} target="_blank" rel="noreferrer">[{id}] </a>)} · See the searchable evidence library for scope and limitations.</p>}
const doors=[['Favorite player','A recognizable player opens the door. What remains when that player leaves?','R05 / R06'],['Family','A shared ritual can make a club feel familiar before you choose it yourself.','R02 / R22'],['World Cup','An event can spark curiosity. A club needs a reason to hold it.','R01'],['Video game','Learning the names is a possible introduction; playing a game is not proof of club attachment.','R21'],['Social media','Repeated encounters can bring a distant club into everyday life.','R21'],['Friends','The people watching with you may become part of what you return for.','R03 / R23'],['First live match','Being there creates an opportunity for connection, not a guarantee.','R03'],['Television','A viewing routine can create familiarity across an ocean.','R21 / R22'],['Local club','Place can supply meaning. A postcode cannot choose your team for you.','R02'],['Playing soccer','Playing can introduce the game without determining which league you watch.','R01']];
const viewerRoles=['Bored / casual viewer','Occasional watcher','Interested follower','Attached supporter','Loyal fan'];
const roleNotes=['It is on. You have time. That can be the whole story.','You choose a match now and then. No membership required.','A player, style or story earns more of your attention.','A club or community has become personally meaningful.','The relationship persists beyond a single result.'];
export function FandomPath(){const [selected,setSelected]=useState<number[]>([]),[role,setRole]=useState(0);return <div id="fandom-path" className="explorer"><span className="label application">Your route / no required destination</span><h3>What role does soccer<br/>actually play in your life?</h3><div className="role-route" aria-label="Your relationship with soccer">{viewerRoles.map((name,i)=><button key={name} aria-pressed={role===i} onClick={()=>setRole(i)}><small>0{i+1}</small>{name}</button>)}</div><div className="role-response" aria-live="polite"><strong>{viewerRoles[role]}</strong><p>{roleNotes[role]}</p><span className="label">Staying here is a valid endpoint.</span></div><h4>What brought it into view?</h4><p className="caption quiet">Choose up to three routes. They can overlap.</p><div className="switches">{doors.map(([name],i)=><button key={name} aria-pressed={selected.includes(i)} disabled={selected.length===3&&!selected.includes(i)} onClick={()=>setSelected(s=>s.includes(i)?s.filter(n=>n!==i):[...s,i])}>{name}</button>)}</div><div className="path-stages" aria-label="Conceptual connections, not required steps">{['Discovery','Attraction','Attachment','Allegiance'].map((stage,i)=><div key={stage} className={i===Math.max(0,role-1)?'path-current':''}><small>{i===Math.max(0,role-1)?'YOUR SELECTED LENS':'POSSIBLE CONNECTION'}</small><strong>{stage}</strong><span>{['I notice it.','I enjoy it.','It means something.','I keep returning.'][i]}</span></div>)}</div><div aria-live="polite" className="path-output">{selected.map(i=><article key={i}><strong>{doors[i][0]}</strong><p>{doors[i][1]}</p><small>Context: {doors[i][2]}</small></article>)}</div><p className="caption quiet">Routes can stop, overlap or reverse. This editorial mapping adapts the PCM’s awareness, attraction, attachment and allegiance; it does not measure your identity or predict progression.</p><details><summary>Research behind the route</summary><Evidence ids={['R01','R02','R20','R21','R22','R23']}/></details></div>}
const rituals=['Matchday routine','Transfer news','Highlights','Podcasts','Supporter friends','Club history'];
export function Presence(){const [chosen,setChosen]=useState<string[]>(['Matchday routine','Supporter friends']);return <div className="presence explorer"><div><span className="eyebrow">Distance vs presence</span><h3>Far away.<br/>Always around.</h3><p>Geography says Missouri. Your shirt says London.</p><p className="caption quiet">Toggle the ways a distant club might show up in a fan’s week. This is an illustrative routine, not an emotional-closeness scale.</p></div><div><div className="switches">{rituals.map(r=><button key={r} aria-pressed={chosen.includes(r)} onClick={()=>setChosen(c=>c.includes(r)?c.filter(x=>x!==r):[...c,r])}>{r}</button>)}</div><div className="presence-orbit" aria-live="polite"><strong>A fan’s everyday life</strong>{chosen.length?chosen.map(r=><span key={r}>{r}</span>):<p>No routines selected. Distance alone still cannot explain attachment.</p>}</div><p className="caption quiet">The ocean stays put. The opportunities for contact change. Local clubs can build these routines too.</p><Evidence ids={['R21','R23']}/></div></div>}
const comparisons=[
['Proximity','A local match can offer in-person rituals and community participation. Travel, price and welcome still matter.','A distant club can be present through viewing groups and media. Access to its home stadium is a different proposition.','Living nearby is an opportunity for contact, not evidence of attachment.'],
['Identity','City symbols and shared local experiences can give a club personal meaning.','An overseas club can connect a fan to heritage, friends or an adopted community.','Local and global identities can coexist. Neither automatically feels more authentic.'],
['Players','A recognizable player can draw attention; linking that interest to the club is a separate task.','A familiar player can introduce an overseas club; that fan may stay for other reasons.','Star recognition, attendance and lasting identification are different outcomes.'],
['History + prestige','A younger club can build rituals around experiences supporters actually share.','An established club’s history can offer stories that a distant supporter adopts.','History cannot be manufactured overnight. Prestige is an association to investigate, not a quality statistic.'],
['Media familiarity','Repeated player and community stories can make the club recognizable between matches.','Viewing routines, digital content and supporter groups can sustain contact from abroad.','Exposure is not the same as affection. Ask what contact means to a fan.'],
['Quality','Look at defined dimensions of the soccer and report the limits of comparable evidence.','Use the same definitions, period and context before interpreting an apparent difference.','No overall league score here. Choose a quality dimension in the next section.']
];
export function LeagueComparison(){const [active,setActive]=useState(0);const c=comparisons[active];return <div className="explorer"><span className="eyebrow">Different forms of value / RQ2</span><h3>Two leagues.<br/>More than one reason.</h3><p>Choose a lens. Leave the winner’s podium in storage.</p><div className="switches" aria-label="Comparison category">{comparisons.map(([name],i)=><button key={name} aria-pressed={active===i} onClick={()=>setActive(i)}>{name}</button>)}</div><div aria-live="polite"><div className="league-pair"><article><span className="eyebrow">MLS / local opportunity</span><h4>{c[0]}</h4><p>{c[1]}</p></article><article><span className="eyebrow">Premier League / overseas connection</span><h4>{c[0]}</h4><p>{c[2]}</p></article></div><p className="comparison-note"><strong>Interpretation: </strong>{c[3]}</p></div><details><summary>Research context and limits</summary><p>These are research-informed comparison lenses, not measured league rankings. Community identity and transnational fandom frame the questions. Historical star-player attendance studies do not establish present-day attachment effects.</p><Evidence ids={['R02','R05','R06','R21','R22','R23']}/></details></div>}
const dimensions=[
{title:'Passing',belief:'“Better teams keep the ball better.”',measure:'Pass completion, progression and pass difficulty, using consistent event definitions.',limit:'Completion alone rewards safe passes. Opponent pressure, field position and game state change the task.'},
{title:'Chance creation',belief:'“More chances means better soccer.”',measure:'Shots, shot locations and expected goals from the same provider and model.',limit:'More chances may reflect weak defending. Expected-goals values from different models are not directly interchangeable.'},
{title:'Possession',belief:'“More of the ball means more quality.”',measure:'Possession share alongside territory, score state and attacking outcomes.',limit:'Possession describes control of the ball, not automatically the value created with it.'},
{title:'Tempo',belief:'“Faster must mean better.”',measure:'Defined measures such as ball-in-play time, sequence duration or progression speed.',limit:'These measure different kinds of speed. Faster decisions, faster running and shorter possessions are not the same thing.'},
{title:'Player profiles',belief:'“Famous players settle the argument.”',measure:'Age, minutes, roles and international representation within a specified season.',limit:'Recognition is not performance. National-team selection depends on eligibility, competition and selection policy.'},
{title:'Competitive balance',belief:'“Unpredictable games mean a stronger league.”',measure:'Points dispersion or outcome concentration over comparable seasons and competition formats.',limit:'Uncertainty of outcome and absolute playing standard are distinct. Different schedules complicate comparison.'},
{title:'Player movement',belief:'“Transfers tell us which league is better.”',measure:'Player minutes and roles before and after a move, with age and adaptation time recorded.',limit:'Transfers are selected cases. A transfer fee or one successful player cannot represent an entire league.'}
];
export function ProductLab(){const [active,setActive]=useState(0);const d=dimensions[active];return <><div className="reputation-grid"><article><span className="eyebrow orange">Premier League associations to examine</span><h3>Historic. Global.<br/>Prestigious?</h3></article><article><span className="eyebrow orange">MLS associations to examine</span><h3>Local. Younger.<br/>Growing?</h3></article></div><p className="caption quiet">Illustrative reputation prompts, not universal beliefs or measured American responses. Cultural and transnational-fandom literature supplies context; it does not establish the prevalence of these labels. <a href="#research">R17 · R21 · R22 · R23</a></p><div className="explorer product-lab"><span className="label">Perception vs product / RQ3</span><h3>The name arrives<br/>before the ball moves.</h3><p>But “quality” needs a definition. Select what you want to examine.</p><div className="switches" aria-label="Quality dimension">{dimensions.map((x,i)=><button key={x.title} aria-pressed={active===i} onClick={()=>setActive(i)}>{x.title}</button>)}</div><div className="product-cards" aria-live="polite"><article><span className="label">01 / Perception prompt</span><h4>{d.belief}</h4><p className="caption">Illustrative assumption to question, not a participant quote or documented finding.</p></article><article><span className="label application">02 / Observable product</span><h4>What could we inspect?</h4><p>{d.measure}</p></article><article><span className="label">03 / Interpretation</span><h4>What does it leave out?</h4><p>{d.limit}</p></article></div><details className="rule"><summary>How this addresses RQ3 responsibly</summary><p>Compare documented perceptions in existing American-fan research with defined characteristics in comparable published soccer data. Record the season, sample, provider and definition. Where matching evidence is unavailable, leave the comparison unresolved.</p><p>The anonymous comparison above uses a supplied snapshot of scoring, shooting, roster and points-spread characteristics. These additional prompts explain what each indicator can and cannot establish; they do not create an overall quality ranking.</p></details><p className="caption quiet">Secondary research only. No blind-evaluation experiment, surveys or participant responses are collected.</p></div></>}
const problems=[
{title:'Low player recognition',issue:'Recognition before attachment',examine:'Star-related attendance effects vary by player and method; attention is not lasting team identity.',influence:'Recurring introductions and player access.',boundary:'Recruitment budgets or an automatic transfer of player loyalty.',actions:['Introduce one player through a recurring short series.','Connect each story to teammates and the city.','Track repeat viewing separately from reach.'],refs:['R05','R06']},
{title:'Weak local attachment',issue:'Proximity without personal meaning',examine:'Community-identity frameworks connect team meaning with wider social groups.',influence:'Local relationships, symbols and welcoming experiences.',boundary:'A postcode cannot guarantee allegiance.',actions:['Partner with a neighborhood organization.','Build an invitation around a shared local experience.','Check whether newcomers return, not just attend once.'],refs:['R02','R20']},
{title:'League reputation gap',issue:'Expectations before experience',examine:'Transnational-fandom research gives familiarity, stars and social influences a role; it does not isolate reputation effects.',influence:'Clear presentation and evidence for specific product claims.',boundary:'Financial scale, accumulated prestige or playing standard through messaging alone.',actions:['Separate prestige objections from access and product objections.','Use the defined league comparison, not a quality slogan.','Offer a low-friction opportunity to experience a match.'],refs:['R21','R22']},
{title:'Weak storytelling',issue:'Exposure without continuity',examine:'Digital football scholarship treats media as a setting for culture and identity, not a guaranteed conversion channel.',influence:'Consistent voices, recurring stories and useful context.',boundary:'No story can promise emotional attachment.',actions:['Choose one ongoing supporter or player story.','Give each installment a reason to return.','Connect online stories to real matchday experiences.'],refs:['R21','R20']},
{title:'Poor supporter identity',issue:'A badge without shared meaning',examine:'Team identity is multidimensional; a purchase alone does not establish belonging.',influence:'Participation, symbols and supporter representation.',boundary:'The club cannot dictate how every supporter identifies.',actions:['Invite supporters to shape a ritual.','Make newcomer participation easy to understand.','Check that club actions match its stated values.'],refs:['R02','R20']},
{title:'Weak community connection',issue:'An audience without relationships',examine:'U.S.-based EPL research associates fan-community attachment with identification and consumption.',influence:'Shared experiences and relationships between viewers.',boundary:'Existing overseas loyalties do not vanish with a local campaign.',actions:['Work with an existing local watch group.','Welcome dual fandom explicitly.','Create a reason to return with someone familiar.'],refs:['R23','R03']},
{title:'Casual viewers do not return',issue:'Convenience without a repeat habit',examine:'The PCM distinguishes attraction from deeper attachment. Watching once is not allegiance.',influence:'Scheduling clarity, easy access and relevant follow-up.',boundary:'Some people want an occasional watch; that is a legitimate endpoint.',actions:['Make the next viewing opportunity easy to find.','Offer an optional reminder or short recap.','Measure repeat viewing separately from club identification.'],refs:['R01','R04']}
];
export function ClubDecision(){const [active,setActive]=useState(0);const p=problems[active];return <><div className="application-photo"><img src="/fcc-supporters.svg" width="1600" height="1067" loading="lazy" alt="FC Cincinnati supporters sharing a matchday with flags and club colors"/><div><span className="eyebrow">From an audience to a community</span><h3>Give the connection<br/>somewhere to go.</h3><p>Practical application: create a reason to return together.</p><a href="#credits">Jamie Smed / CC BY 2.0 · Image credit</a></div></div><div className="fan-transition"><span className="eyebrow orange">The soccer fan MLS doesn’t have to convince</span><h3>Loves soccer. Watches soccer.<br/>Buys the shirt. Knows the players.</h3><p>Still might not care about MLS.</p><strong>So where did the attachment go?</strong></div><ControlExplorer/><div className="explorer decision-tool"><span className="label application">Foreign Colors Playbook</span><h3>What problem are you<br/>trying to solve?</h3><div className="decision-layout"><div className="decision-options" aria-label="Choose an organizational challenge">{problems.map((x,i)=><button key={x.issue} aria-pressed={active===i} onClick={()=>setActive(i)}>{x.title}<span aria-hidden="true">↗</span></button>)}</div><div className="decision-result" aria-live="polite"><span className="eyebrow orange">Possible issue</span><h4>{p.issue}</h4><dl><dt>Research suggests</dt><dd>{p.examine}</dd><dt>You may influence</dt><dd>{p.influence}</dd><dt>Marketing cannot do it alone</dt><dd>{p.boundary}</dd></dl><span className="label application">Professional interpretation / actions to test</span><ol className="play-actions">{p.actions.map(action=><li key={action}>{action}</li>)}</ol><details><summary>Evidence & limitations</summary>{p.refs.map(id=>{const source=sources.find(s=>s.id===id)!;return <p key={id} className="caption quiet">{source.limit}</p>})}<Evidence ids={p.refs}/></details><button className="btn outline" onClick={()=>{const text=["FOREIGN COLORS PLAYBOOK",p.title,"Research lens: "+p.examine,"Can influence: "+p.influence,"Cannot control: "+p.boundary,"Actions to test:",...p.actions.map((a,i)=>`${i+1}. ${a}`),"Research-informed application, not a validated diagnosis or promised result.",...p.refs.map(id=>{const s=sources.find(s=>s.id===id)!;return `${id}: ${s.url} — ${s.limit}`})].join("\n\n");const url=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="Foreign-Colors-Action-Plan.txt";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Download this action plan ↓</button></div></div><p className="caption quiet">A planning aid, not a validated diagnosis or a promised result. The cited research informs the lens; the proposed action is an application to test.</p></div></>}
