import {useState} from 'react';
import {preferenceFactors} from './data';

export function DistanceProblem(){
 const [route,setRoute]=useState('both');
 return <div className="distance-case"><div className="case-heading"><span className="eyebrow">Field note 01 / The distance problem</span><p>Your postcode has entered the chat.</p></div><div className="route-selector" aria-label="Explore a fan’s possible club connections">{[['local','Stay local'],['foreign','Cross the Atlantic'],['both','Keep both scarves']].map(([id,label])=><button key={id} aria-pressed={route===id} onClick={()=>setRoute(id)}>{label}</button>)}</div><div className="route-spread"><figure className={route==='foreign'?'route-photo subdued':'route-photo'}><img src="/stl-supporters.svg" width="1800" height="811" loading="lazy" alt="St. Louis CITY supporters raising scarves"/><figcaption><span>Home connection</span><strong>St. Louis, USA</strong><small>A club in your city.</small></figcaption></figure><div className="route-center"><span className="eyebrow">An American fan</span><div className="route-link" aria-hidden="true">↔</div><p aria-live="polite">{route==='local'?'The trip is shorter. The attachment still needs a reason.':route==='foreign'?'The club is overseas. The group chat is extremely local.':'Two scarves. One neck. We believe in you.'}</p></div><figure className={route==='local'?'route-photo subdued':'route-photo'}><img src="/stamford-bridge.svg" width="1400" height="667" loading="lazy" alt="Stamford Bridge, Chelsea’s home stadium in London"/><figcaption><span>Foreign connection</span><strong>London, England</strong><small>A club across an ocean.</small></figcaption></figure></div><p className="caption quiet">Illustrative St. Louis–London comparison, not a distance scale or a prediction of preference. Geography and emotional closeness are different questions. <a href="#credits">Photo credits ↓</a></p></div>
}

export function EvidenceBoard(){
 const [pins,setPins]=useState<number[]>([]),[active,setActive]=useState(0);
 function pin(i:number){setActive(i);setPins(p=>p.includes(i)?p.filter(n=>n!==i):[...p,i]);}
 return <div className="evidence-case"><div className="case-heading"><span className="eyebrow">Field note 02 / The fan evidence board</span><h3>Follow the clues.<br/>Leave the verdict open.</h3><p>Pin the influences you would investigate. There is no “correct fan” hiding at the end.</p></div><div className="evidence-workspace"><div className="evidence-notes" aria-label="Pin possible influences">{preferenceFactors.map((f,i)=><button className={'evidence-note note-'+i} key={f.name} aria-pressed={pins.includes(i)} onClick={()=>pin(i)}><span className="pin-state">{pins.includes(i)?'PINNED ✓':'PIN THIS +'} <span>0{i+1}</span></span><strong>{f.name}</strong><small>{['Home is a clue, not a contract.','A badge can feel like a belonging.','Who briefed your eyeballs?','One highlight. A lifelong subscription.','Sometimes the remote decides.'][i]}</small></button>)}</div><aside className="case-file" aria-live="polite"><span className="eyebrow">Your open case / {pins.length} pinned</span><h3>{pins.length?'Interesting. Keep digging.':'No suspects yet.'}</h3><p>{pins.length?pins.map(i=>preferenceFactors[i].name).join(' + '):'Pick a clue to start your investigation.'}</p><hr/><span className="label">Under the magnifying glass</span><h4>{preferenceFactors[active].title}</h4><p>{preferenceFactors[active].question}</p><details><summary>What to investigate</summary><p>{preferenceFactors[active].explore}</p><p><strong>Do not assume: </strong>{preferenceFactors[active].caution}</p></details>{pins.length>0&&<button className="text-button" onClick={()=>setPins([])}>Clear the board ↺</button>}</aside></div><p className="caption quiet">An exploration tool, not a personality score or survey. Selections stay on this page and disappear when you reload. Possible influences are not ranked by importance.</p></div>
}

export function RevealColors(){
 const [reaction,setReaction]=useState(''),[revealed,setRevealed]=useState(false);
 return <div className="reveal-case"><div className="case-heading"><span className="eyebrow orange">Field note 03 / Reveal the colors</span><h3>First the place.<br/>Then the name.</h3><p>A stadium photograph, not a test of playing quality. Look first. Pick a reaction. Then lift the label.</p></div><div className="reveal-layout"><figure className={'reveal-photo '+(revealed?'is-revealed':'')}><img src="/stamford-bridge.svg" width="1400" height="667" loading="lazy" alt={revealed?'Stamford Bridge, Chelsea’s stadium in London':'Stadium photograph with its location label withheld; visible features may identify it'}/><figcaption aria-live="polite"><span className="eyebrow">{revealed?'Identity revealed':'Location label withheld'}</span><strong>{revealed?'STAMFORD BRIDGE':'EXHIBIT 01'}</strong><span>{revealed?'Chelsea · London, England':'The photo may still give you clues.'}</span></figcaption></figure><div className="reveal-controls"><span className="label">Your first impression</span><div className="reaction-options" aria-label="Choose your first impression">{['I would take a seat.','I need the backstory.','Not my scene.'].map(r=><button key={r} aria-pressed={reaction===r} disabled={revealed} onClick={()=>setReaction(r)}>{r}</button>)}</div><button className="btn" disabled={!reaction||revealed} onClick={()=>setRevealed(true)}>Reveal the colors ↗</button><div className="reveal-response" aria-live="polite">{revealed?<><p><strong>You said: “{reaction}”</strong></p><p>Did “Chelsea” change anything? Keep that thought. It is a question, not a diagnosis.</p><button className="text-button" onClick={()=>{setReaction('');setRevealed(false)}}>Reset the scene ↺</button></>:<p className="quiet">{reaction?'Your first impression is in. Shall we introduce the landlord?':'Choose a reaction to unlock the reveal.'}</p>}</div></div></div><p className="caption quiet">Personal reflection only. No responses are collected or saved. The initial image is shown in grayscale; this changes the visual experience, so it cannot isolate a branding effect. Architecture, seats and signs can reveal identity. <a href="#credits">Photography credit ↓</a></p></div>
}
