import {useState} from 'react';
import {sources} from './data';
const findings=[
 {title:'Community matters across distance.',kind:'Existing study / U.S.-based EPL fans',evidence:'753',unit:'surveyed fans',detail:'Fan-community attachment was associated with identification and consumption.',meaning:'The relationship can include the people around the club.',action:'Explore shared experiences alongside geographic proximity.',ids:['R23']},
 {title:'Supporters do not always attend alone.',kind:'Existing study / American soccer supporters',evidence:'Shared ties',unit:'and co-attendance',detail:'Shared supporter-group membership and team-setting interactions were associated with greater co-attendance.',meaning:'Attendance is also a social question.',action:'Create opportunities for people to return together.',ids:['R03']},
 {title:'A famous name is not a universal formula.',kind:'Historical MLS attendance research',evidence:'Mixed effects',unit:'across players and methods',detail:'Beckham-era research found an attendance effect; designated-player estimates were sensitive to method and player inclusion.',meaning:'Star attention cannot stand in for evidence of lasting attachment.',action:'Track repeat interest separately from a star-driven visit.',ids:['R05','R06']},
 {title:'Attention and allegiance are different.',kind:'Conceptual framework / not an empirical finding',evidence:'4 levels',unit:'of psychological connection',detail:'The PCM distinguishes awareness, attraction, attachment and allegiance.',meaning:'An occasional viewer does not have to become a loyal supporter.',action:'Match the invitation to the relationship people actually want.',ids:['R01']}
];
export function FindingsHub(){const [active,setActive]=useState(0);const f=findings[active];return <section id="findings" className="section paper"><div className="wrap"><div className="section-head"><div><span className="eyebrow">The findings desk / existing evidence</span><h2>What holds up?</h2></div><p className="quiet">Published evidence and frameworks. No invented thesis results.</p></div><div className="finding-tabs" aria-label="Explore supported research">{findings.map((x,i)=><button key={x.title} aria-pressed={active===i} onClick={()=>setActive(i)}><small>0{i+1}</small>{x.title}</button>)}</div><div className="finding-spread" aria-live="polite"><div className="finding-fact"><span className="eyebrow">Evidence</span><strong>{f.evidence}</strong><span>{f.unit}</span><p className="caption">{f.kind}</p></div><div><h3>{f.title}</h3><p>{f.detail}</p><div className="finding-meaning"><div><span className="label">Interpretation</span><p>{f.meaning}</p></div><div><span className="label application">Practical implication</span><p>{f.action}</p></div></div><details><summary>Sources, sample & limits</summary>{f.ids.map(id=>{const s=sources.find(s=>s.id===id)!;return <div key={id}><p className="caption">{s.limit}</p><a className="source-link" href={s.url} target="_blank" rel="noreferrer">{id} · {s.authors} ({s.year}) ↗</a></div>})}</details></div></div><div className="myth-strip"><span className="eyebrow">Shortcut thinking / tap to question it</span>{[['Closer team = stronger fandom','Not automatically. Community and adopted identities can matter across distance.','R23'],['Better soccer = automatic loyalty','Enjoyment and enduring attachment are different questions in the PCM.','R01'],['Casual viewers are already fans','Attention alone does not establish allegiance. Casual viewing can remain casual.','R01']].map(([myth,reply,id])=><details key={myth}><summary>“{myth}”</summary><p>{reply} <a href={sources.find(s=>s.id===id)!.url} target="_blank" rel="noreferrer">[{id}] ↗</a></p></details>)}</div></div></section>}
const forces=[['Product','The soccer you enjoy watching.'],['Identity','The club that feels like part of you.'],['Geography','The places you can reach and the places you call home.'],['Reputation','The expectations that arrive before kickoff.'],['Media','The match, highlight or story that keeps showing up.'],['History','The past you inherit or choose to adopt.'],['Community','The people who make the connection feel close.']];
export function ClosingRoute(){const [active,setActive]=useState(1);return <section id="closer" className="section closing-route"><div className="wrap"><span className="eyebrow">Home / away / where the connection lives</span><h2>Foreign colors.<br/>Close to home.</h2><div className="closing-lines" aria-hidden="true"><span>PHYSICAL DISTANCE</span><i/><span>EMOTIONAL CLOSENESS</span></div><h3>Why can a faraway club feel closer?</h3><div className="closing-forces" aria-label="Explore the forces behind attachment">{forces.map(([name],i)=><button key={name} aria-pressed={active===i} onClick={()=>setActive(i)}>{name}</button>)}</div><p className="closing-answer" aria-live="polite">{forces[active][1]}</p><p className="closing-takeaway">A club can be far from your address and present in your life.</p><p className="caption">Interpretive synthesis, not a causal model. Different people combine these forces differently. <a href="#findings">Follow the evidence ↑</a></p></div></section>}
